name: Test API
on: push
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-python
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
    - name : PIP install
      run : pip install -r requirements.txt
    - name : Test
      run : python tests.py

